import { createAccessControl } from 'better-auth/plugins/access'
import {
  adminAc,
  defaultStatements,
} from 'better-auth/plugins/organization/access'

export const statements = {
  ...defaultStatements,
  organization: ['update', 'delete'],
  member: ['create', 'update', 'delete'],
  invitation: ['create', 'cancel'],
  team: ['create', 'update', 'delete'],
  ac: ['create', 'read', 'update', 'delete'],
  project: ['create', 'read', 'update', 'delete'],
  requirement: [
    'create',
    'read',
    'update',
    'delete',
    'send_for_sign',
    'request_changes',
    'resolve_changes',
    'reject_changes',
  ],
  invoice: [
    'create',
    'read',
    'update',
    'delete',
    'send',
    'sign',
    'request_changes',
  ],
  thread: ['create', 'read', 'update', 'resolve', 'reply'],
  time_entry: [
    'create',
    'read',
    'update',
    'delete',
    'submit',
    'approve',
    'reject',
  ],
  member_rate: ['manage'],
  project_budget: ['manage'],
  timesheet_report: ['create', 'read', 'send', 'approve', 'dispute'],
  milestone: ['create', 'read', 'update', 'delete', 'complete'],
  proposal: ['create', 'read', 'update', 'delete', 'send', 'sign'],
  expense: [
    'create',
    'read',
    'update',
    'delete',
    'submit',
    'approve',
    'reject',
  ],
  expense_category: ['create', 'read', 'update', 'delete'],
} as const

export const ac = createAccessControl(statements)

export const ownerRole = ac.newRole({
  ...adminAc.statements,
  organization: ['update', 'delete'],
  member: ['create', 'update', 'delete'],
  invitation: ['create', 'cancel'],
  team: ['create', 'update', 'delete'],
  ac: ['create', 'read', 'update', 'delete'],
  project: ['create', 'read', 'update', 'delete'],
  requirement: [
    'create',
    'read',
    'update',
    'delete',
    'send_for_sign',
    'request_changes',
    'resolve_changes',
    'reject_changes',
  ],
  invoice: [
    'create',
    'read',
    'update',
    'delete',
    'send',
    'sign',
    'request_changes',
  ],
  thread: ['create', 'read', 'update', 'resolve', 'reply'],
  time_entry: [
    'create',
    'read',
    'update',
    'delete',
    'submit',
    'approve',
    'reject',
  ],
  member_rate: ['manage'],
  project_budget: ['manage'],
  timesheet_report: ['create', 'read', 'send', 'approve', 'dispute'],
  milestone: ['create', 'read', 'update', 'delete', 'complete'],
  proposal: ['create', 'read', 'update', 'delete', 'send', 'sign'],
  expense: [
    'create',
    'read',
    'update',
    'delete',
    'submit',
    'approve',
    'reject',
  ],
  expense_category: ['create', 'read', 'update', 'delete'],
})

export const adminRole = ac.newRole({
  ...adminAc.statements,
  organization: ['update'],
  member: ['create', 'update', 'delete'],
  invitation: ['create', 'cancel'],
  team: ['create', 'update', 'delete'],
  ac: ['create', 'read', 'update', 'delete'],
  project: ['create', 'read', 'update', 'delete'],
  requirement: [
    'create',
    'read',
    'update',
    'delete',
    'send_for_sign',
    'request_changes',
    'resolve_changes',
    'reject_changes',
  ],
  invoice: [
    'create',
    'read',
    'update',
    'delete',
    'send',
    'sign',
    'request_changes',
  ],
  thread: ['create', 'read', 'update', 'resolve', 'reply'],
  time_entry: [
    'create',
    'read',
    'update',
    'delete',
    'submit',
    'approve',
    'reject',
  ],
  member_rate: ['manage'],
  project_budget: ['manage'],
  timesheet_report: ['create', 'read', 'send', 'approve', 'dispute'],
  milestone: ['create', 'read', 'update', 'delete', 'complete'],
  proposal: ['create', 'read', 'update', 'delete', 'send'],
  expense: [
    'create',
    'read',
    'update',
    'delete',
    'submit',
    'approve',
    'reject',
  ],
  expense_category: ['create', 'read', 'update', 'delete'],
})

export const memberRole = ac.newRole({
  organization: [],
  member: [],
  invitation: [],
  team: [],
  ac: ['read'],
  project: ['read'],
  requirement: ['create', 'read', 'update'],
  invoice: [],
  thread: ['create', 'read', 'update'],
  time_entry: ['create', 'read', 'update', 'delete', 'submit'],
  member_rate: [],
  project_budget: [],
  timesheet_report: ['read'],
  milestone: ['read'],
  proposal: ['read'],
  expense: ['create', 'read', 'update', 'delete', 'submit'],
  expense_category: ['read'],
})

export const clientRole = ac.newRole({
  organization: [],
  member: [],
  invitation: [],
  team: [],
  ac: ['read'],
  project: ['read'],
  requirement: ['read', 'request_changes', 'resolve_changes', 'reject_changes'],
  invoice: ['read', 'sign', 'request_changes'],
  thread: ['create', 'read', 'resolve', 'reply'],
  time_entry: [],
  member_rate: [],
  project_budget: [],
  timesheet_report: ['read', 'approve', 'dispute'],
  milestone: ['read'],
  proposal: ['read', 'sign'],
  expense: ['read', 'approve', 'reject'],
  expense_category: ['read'],
})

export const roles = {
  owner: ownerRole,
  admin: adminRole,
  member: memberRole,
  client: clientRole,
} as const
