'use server'

import { and, eq } from 'drizzle-orm'
// import { PROJECTS_CACHE_TAG } from '@/api/projects/service'
import { authedActionClient } from '@/lib/safe-action'
import { titleToSlug } from '@/lib/utils'
import { db } from '@/server/db'
import { projects, requirements } from '@/server/db/schema'
import { createProjectSchema } from './common'

export const createProjectAction = authedActionClient
  .inputSchema(createProjectSchema)
  .action(
    async ({
      parsedInput: { organizationId, name, description, dueDate },
      ctx: { orgMember, role },
    }) => {
      if (!role.authorize({ project: ['create'] }).success) {
        throw new Error('You do not have permission to create projects')
      }

      if (orgMember.organizationId !== organizationId) {
        throw new Error('Workspace mismatch')
      }
      const { slugified, slugifiedWithSuffix } = titleToSlug(name)

      const project = await db.transaction(async (tx) => {
        const [projectWithSlug] = await tx
          .select()
          .from(projects)
          .where(
            and(
              eq(projects.organizationId, organizationId),
              eq(projects.slug, slugified)
            )
          )
        const [project] = await tx
          .insert(projects)
          .values({
            name,
            slug: projectWithSlug ? slugifiedWithSuffix : slugified,
            description: description || null,
            organizationId,
            dueDate: dueDate ?? null,
          })
          .returning()

        // This is the requirement called "General Work"
        await tx.insert(requirements).values({
          projectId: project!.id,
          slug: 'saturn_default_general_work',
          title: 'General Work',
          body: '<h1> This is a default requirement generated by Saturn to categorize under General Work <h1>',
          status: 'client_accepted',
          authorId: orgMember.id,
        })

        return project
      })

      // revalidateTag(PROJECTS_CACHE_TAG,"max")
      return project
    }
  )
